### ISSUE TITLE
SQL Azure support

### ISSUE THREAD

**Issue by meet-bhagdev** [aaugustin/django-pymssql#6]
Does this support SQL Azure?
Could not find it in the documentation.

**Comment by aaugustin** [comment]
I have no idea. Try it and let me know? :-)

**Comment by meet-bhagdev** [comment]
Having trouble with that. On a side note, does this work Linux? I see SQL Server Express is a pre req

**Comment by aaugustin** [comment]
Most likely, that means you're getting an import error. Try running `import sqlserver_pymssql` in a Python shell (i.e. `./manage.py shell`) and see if that helps you find the problem.

**Comment by meet-bhagdev** [comment]
if i run import sqlserver_pymssql in the python shell in linux, it works just fine.
>>> import sqlserver_pymssql

**Comment by aaugustin** [comment]
Can you try `import sqlserver_pymssql.base` as well?

**Comment by aaugustin** [comment]
(Sorry, I know remote debugging over GitHub Issues is frustrating, I'm doing my best...)

**Comment by meet-bhagdev** [comment]
No worries! Thank you for the help. This is what I get : 

Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlserver_pymssql.base
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/sqlserver_pymssql/base.py", line 7, in <module>
    from sqlserver_ado.base import (
  File "/usr/local/lib/python2.7/dist-packages/sqlserver_ado/base.py", line 16, in <module>
    from .operations import DatabaseOperations
  File "/usr/local/lib/python2.7/dist-packages/sqlserver_ado/operations.py", line 20, in <module>
    from . import fields as mssql_fields
  File "/usr/local/lib/python2.7/dist-packages/sqlserver_ado/fields.py", line 4, in <module>
    from django.db import models
  File "/usr/lib/python2.7/dist-packages/django/db/models/__init__.py", line 5, in <module>
    from django.db.models.query import Q
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 17, in <module>
    from django.db.models.deletion import Collector
  File "/usr/lib/python2.7/dist-packages/django/db/models/deletion.py", line 4, in <module>
    from django.db.models import signals, sql
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/__init__.py", line 4, in <module>
    from django.db.models.sql.subqueries import *
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/subqueries.py", line 12, in <module>
    from django.db.models.sql.query import Query
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 22, in <module>
    from django.db.models.sql import aggregates as base_aggregates_module
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/aggregates.py", line 9, in <module>
    ordinal_aggregate_field = IntegerField()
  File "/usr/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 116, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by aaugustin** [comment]
You're just running `python` here so your Django settings aren't configured.

Try running `./manage.py shell` or setting the `DJANGO_SETTINGS_MODULE` environment variable to the dotted Python path to your settings module — both have the same effect.

**Comment by bratomes** [comment]
I received the following error when I try import sqlserver_pymssql.base: ImportError: No module named 'django.db.backends.util'. I'm using Django 1.9

**Comment by aaugustin** [comment]
Either you're using incompatible versions of django-mssql and Django, or you haven't installed Django correctly. It's hard to tell from the limited amount of information you provided.

**Comment by meet-bhagdev** [comment]
Django pymssql only runs on 1.7 and below as far as I am aware. @Bruno any updates on your end?

_____________________________
